### ISSUE TITLE
Need task queues for go-fula

### ISSUE THREAD

**Issue by farhoud** [functionland/go-fula#45]
## Problem 
go-fula/mobile is based on a P2P network and targets mobile devices. so we end up with a very unstable network:
- users may want to upload and download only on WIFI.
- box behind nat does not always connect on the first try. #32 
- for peer routing, we have to at least connect to 5 to 10 nodes and it takes time. #37 
- user wants the status of the download and upload progress. [#prog](https://github.com/functionland/react-native-fula/issues/12)
With the above knowledge and test that I have done. the chance of the user calling our API and getting an error is very high. 

## Solution
Add task queues and task status API to go-fula/mobile

**Comment by mehdibalouchi** [comment]
@farhoud thank you for this detailed description of the issue.
Right now every request/response on both of our protocols is happening statelessly. When you talk about task status (something like download/upload progress) aren't you mentioning that the connection between the blox and the client should be stateful? We can create a session on every request from the client and then handle these sessions with a task queue or a session manager. Of course we are able to manage a task queue without creating any session objects, but I think solving the problem using a session can help us with other features as well (e.g. ability to pause and resume downloads)

**Comment by farhoud** [comment]
@mehdibalouchi I think we need both:
Task management will handle: 




> * users may want to upload and download only on WIFI.
> 
> * box behind nat does not always connect on the first try.
>
> * for peer routing, we have to at least connect to 5 to 10 nodes and it takes time. https://github.com/functionland/go-fula/issues/37

and Session needed to handle:

> * user wants the status of the download and upload progress. [#prog](https://github.com/functionland/react-native-fula/issues/12)

**Comment by mehdibalouchi** [comment]
If I'm understating correctly, Task Management happens on the client side, and the Session management is handled by the Blox. If this is the case, then both the client and the blox should be aware of the sessions, therefore it has to be included in the protocol specification.
About Task management, since it is handled on the client side (it is basically a queue ensuring that a certain task will happen when the conditions are met), there is no need for Blox to be aware of it, so it should not be present in the protocol.
@farhoud is there anything about a 'Task' that the blox should know about it? if so, then we should consider adding it to the protocol specification.

**Comment by farhoud** [comment]
@mehdibalouchi 
Exactly Task is related to Application <--> API interactions and Blox does not need to know about them.
